name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: listendev/action@v0.10
        with:
          jwt: ${{ secrets.LS }}
          ci: only
      - uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install --no-update --no-root

      - name: Run tests
        run: poetry run pytest
